=== Indresh10/web-stack/doctor.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="doclist">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="doc" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="spec" type="xs:string" />
                            <xs:element name="qual" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Indresh10/web-stack/doctor.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="doc.xsl" type="text/xsl"?>
<doclist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./doctor.xsd">
    <doc>
        <id>1</id>
        <name>dlhfkdhf</name>
        <spec>bone</spec>
        <qual>MBBS MDS</qual>
    </doc>
    <doc>
        <id>2</id>
        <name>dfdfg</name>
        <spec>heart</spec>
        <qual>MBBS MDS</qual>
    </doc>
    <doc>
        <id>3</id>
        <name>fdggdfg</name>
        <spec>skin</spec>
        <qual>MBBS MDS</qual>
    </doc>
    <doc>
        <id>4</id>
        <name>dgsf</name>
        <spec>bone</spec>
        <qual>MBBS MDS</qual>
    </doc>
    <doc>
        <id>5</id>
        <name>dlhfkdhf</name>
        <spec>ENT</spec>
        <qual>MBBS MDS</qual>
    </doc>
</doclist>
