=== Indresh10/web-stack/patient.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="patlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="patient" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="address" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Indresh10/web-stack/patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="pat.xsl" type="text/xsl"?>
<patlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./patient.xsd">
    <patient>
        <id>1</id>
        <name>skhdks</name>
        <address>Bangalore</address>
    </patient>
    <patient>
        <id>5</id>
        <name>skhfdf</name>
        <address>Shimla</address>
    </patient>
    <patient>
        <id>3</id>
        <name>sdgfjlfdj</name>
        <address>Hyderabad</address>
    </patient>
    <patient>
        <id>2</id>
        <name>dsfsdf</name>
        <address>Mumbai</address>
    </patient>
    <patient>
        <id>4</id>
        <name>sfsgfg</name>
        <address>Mysore</address>
    </patient>
</patlist>
